[package]
name = "wsprspots"
version = "0.0.0"
authors = ["Mikael Voss <mvs@nya.yt>"]
edition = "2018"

[dependencies]
chrono = "*"
modtype = "*"
num-traits = "*"
num-derive = "*"
unicase = "*"

[profile.release]
lto = true
